### PR TITLE
Fix utf8 character handling

### LINKED ISSUE #20: Chinese characters error
### code
```javascript
const hashJs = require('hash.js');
const crypto = require('crypto');

const data = '您好';
const secret = '48f38d0c6a344959cc94502b7b5e8dffb6a5f41795d9066fc9a649557167ee2f';

const sign1 = crypto.createHmac('sha256', secret).update(data).digest().toString('hex');
console.log(sign1);

const sign2 = hashJs.hmac(hashJs.sha256, secret).update(data).digest('hex');
console.log(sign2);

const data2 = 'Hello';
const sign3 = crypto.createHmac('sha256', secret).update(data2).digest().toString('hex');
console.log(sign3);

const sign4 = hashJs.hmac(hashJs.sha256, secret).update(data2).digest('hex');
console.log(sign4);
```

### output
```
ed66747647585e603e6d238672835c08eb2ca2c65236c3ccc98f29b35ed59713
a0111f22fef8f089040349d10b7444cd9b675bbe0691be5e7cbecc2c32058549
821d65b3425a472512d5ee1ea6c15bd89603489589e662821f177bab610a7a1b
821d65b3425a472512d5ee1ea6c15bd89603489589e662821f177bab610a7a1b
```

- os: Windows 10
- node: v8.11.3

### PR DESCRIPTION
**Pull request by kachkaev**
This PR brings parity between `hash.js` and Node.js `crypto` module, which is crucial for distributed systems. Prior to the fix, utf8 characters were not correctly converted to a byte array and this produced different hash values compared to what `crypto`'s functions did.

Fixes https://github.com/indutny/hash.js/issues/20

I had to remove Node 4 from Travis as it was [failing](https://travis-ci.org/indutny/hash.js/builds/461733657) anyway. This Node version reached its end of life half a year ago, so hope this is fine. Testing for Node 8 and 10 was added.

It'd be great if the patch was released as v2.0.0 as it imposes a breaking change to the hash outputs. We should also describe the changes on the [releases page](https://github.com/indutny/hash.js/releases) to help folks with upgrading.

### CODE REVIEW

File: lib/hash/utils.js [hunk 1]
```diff
@@ -13,14 +13,32 @@ function toArray(msg, enc) {
...
-        if (hi)
-          res.push(hi, lo);
-        else
-          res.push(lo);
+        if (c < 128) {
+          res[p++] = c;
+        } else if (c < 2048) {
+          res[p++] = (c >> 6) | 192;
+          res[p++] = (c & 63) | 128;
+        } else if (
```
Comment (indutny) [inline lib/hash/utils.js]: What do you think about having a function `isSurrogatePair()`?

**Review by indutny — APPROVED** [review]
One comment, otherwise LGTM

File: lib/hash/utils.js (hunk 1 above)
Comment (kachkaev) [reply lib/hash/utils.js]: Where else can we use it? IMO if the only application of `isSurrogatePair()` remains within one `if`, extracting a function won't add much value. However, it will definitely carry a bit of a performance overhead, which a vote against doing so.

The whole code block that generates the utf8 byte array from a JS utf16 string is pretty low-level. Making one tiny bit in it a bit more clear won't make the rest of the lines less cryptic 😅

Comment (indutny) [reply lib/hash/utils.js]: It won't carry any performance overhead :wink: V8 (and other JS engines) are clever enough to inline it. What's going to better, though, is that the code at this line will become much more readable.

Comment (kachkaev) [reply lib/hash/utils.js]:
```js
if ((c & 0xFC00) == 0xD800) && (i + 1) < msg.length &&
            ((msg.charCodeAt(i + 1) & 0xFC00) == 0xDC00)) {
  // ...
}
```

↓

```js
const isSurrogatePair = (msg, i) =>
  (msg.charCodeAt(i) & 0xFC00) == 0xD800)
  && (i + 1) < msg.length && ((msg.charCodeAt(i + 1) & 0xFC00) == 0xDC00)

// ...

if (isSurrogatePair(msg, i)) {
  // ...
}
```

? 🤔

Comment (indutny) [reply lib/hash/utils.js]: How about:
```js
function isSurrogatePair(msg, i) {
  if ((msg.charCodeAt(i) & 0xFC00) !== 0xD800) {
    return false;
  }
  if (i + 1 >= msg.length) {
    return false;
  }
  return (msg.charCodeAt(i + 1) & 0xFC00) === 0xDC00;
}
```

This function could be defined in a top-level scope in this file.

Comment (kachkaev) [reply lib/hash/utils.js]: 👌 

Will just change this:

```diff
 if (i + 1 >= msg.length) {
 if (i < 0 || i + 1 >= msg.length) {
   return false;
 }
```

**Review by indutny — APPROVED** [review]
LGTM

**Comment by indutny** [comment]
Published in 1.1.6

**Comment by kachkaev** [comment]
OK! 🎉

Hope that versioning it as `1.1.6` instead of `2.0.0` won't magically break too many things! 😬 🤞

**Comment by indutny** [comment]
We can always revert it :grin:

**Comment by indutny** [comment]
Thanks for the patch!
